2019-01-08 13:35:00,229 [schedulerFactory_Worker-1] WARN  com.pa.mng.server.system.applicationservice.EventTrafficApplicationServiceImpl - parseAndSaveResults() - unable to get data for policy engine named:'email-esg.demo.com' skipping its result. Exception is:
java.util.concurrent.ExecutionException: com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.pa.mng.server.system.applicationservice.EventTrafficApplicationServiceImpl.parseAndSaveResults(EventTrafficApplicationServiceImpl.java:210)
	at com.pa.mng.server.system.applicationservice.EventTrafficApplicationServiceImpl.synchEventTraffic(EventTrafficApplicationServiceImpl.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at com.pa.fw.common.context.spring.aop.AbstractUserContextAdvice.invoke(AbstractUserContextAdvice.java:101)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at com.pa.fw.server.transactions.spring.aop.TransactionInterceptor.invoke(TransactionInterceptor.java:89)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.pa.fw.common.context.spring.aop.AbstractUserContextAdvice.invoke(AbstractUserContextAdvice.java:101)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.pa.fw.common.context.spring.aop.AbstractUserContextAdvice.invoke(AbstractUserContextAdvice.java:101)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.pa.fw.common.context.spring.aop.AbstractUserContextAdvice.invoke(AbstractUserContextAdvice.java:101)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.pa.fw.common.context.spring.aop.AbstractUserContextAdvice.invoke(AbstractUserContextAdvice.java:101)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.pa.fw.common.context.spring.aop.AbstractUserContextAdvice.invoke(AbstractUserContextAdvice.java:101)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy147.synchEventTraffic(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.pa.fw.common.facade.spring.aop.BaseFacadeAdapterInvocationHandler$MethodInfo.invoke(BaseFacadeAdapterInvocationHandler.java:82)
	at com.pa.fw.common.facade.spring.aop.SimpleFacadeAdapterInvocationHandler.invoke(SimpleFacadeAdapterInvocationHandler.java:36)
	at com.sun.proxy.$Proxy234.synchEventTraffic(Unknown Source)
	at com.pa.mng.server.jobs.EventTrafficJob.execute(EventTrafficJob.java:46)
	at com.pa.fw.server.scheduler.quartz.QuartzJob.execute(QuartzJob.java:109)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:117)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:208)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:124)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
	at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:178)
at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy380.getEventTraffic(Unknown Source)
	at com.pa.mng.server.system.applicationservice.EventTrafficImporter.call(EventTrafficImporter.java:28)
	at com.pa.mng.server.system.applicationservice.EventTrafficImporter.call(EventTrafficImporter.java:15)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)
	... 19 more
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:270)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 32 more
Caused by: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at com.safelogic.cryptocomply.jcajce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:113)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
	... 38 more
Caused by: com.safelogic.cryptocomply.jcajce.provider.AnnotatedException: TrustAnchor found but certificate validation failed.
	at com.safelogic.cryptocomply.jcajce.provider.CertPathValidatorUtilities.findTrustAnchor(CertPathValidatorUtilities.java:211)
	at com.safelogic.cryptocomply.jcajce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:108)
	... 40 more
Caused by: java.security.SignatureException: Signature does not match.
	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449)
	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:392)
	at com.safelogic.cryptocomply.jcajce.provider.CertPathValidatorUtilities.verifyX509Certificate(CertPathValidatorUtilities.java:1187)
	at com.safelogic.cryptocomply.jcajce.provider.CertPathValidatorUtilities.findTrustAnchor(CertPathValidatorUtilities.java:198)
	... 41 more
2019-01-08 13:35:13,708 [ajp-nio-127.0.0.1-17442-exec-9] WARN  org.apache.http.client.protocol.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: visid_incap_544856=Rbb9qWeRTGCC6j7Dbb0jy6amNFwAAAAAQUIPAAAAAAAridws+C/2K+9QsEUPU7oU; expires=Wed, 08 Jan 2020 12:23:29 GMT; path=/; Domain=.skyfence.com". Invalid 'expires' attribute: Wed, 08 Jan 2020 12:23:29 GMT
2019-01-08 13:35:13,710 [ajp-nio-127.0.0.1-17442-exec-9] ERROR com.pa.mng.server.webservices.utils.RestServiceInvoker - isResponseOK(): request returned HttpStatus = 403
2019-01-08 13:35:13,710 [ajp-nio-127.0.0.1-17442-exec-9] ERROR com.forcepoint.mng.server.cloudservice.applicationservice.CASBServiceApplicationServiceImpl - getCASBServiceAccessToken(): cannot get access token - status code is Forbidden
2019-01-08 13:35:13,724 [ajp-nio-127.0.0.1-17442-exec-9] ERROR com.forcepoint.mng.server.cloudservice.applicationservice.CASBServiceApplicationServiceImpl - connectCASBService(): no CASB access token was accepted !!!
